// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobixAPI.Data;

#nullable disable

namespace MobixAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701140600_AddInstallmentMonths")]
    partial class AddInstallmentMonths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("MobixAPI.Models.AgentChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentChats");
                });

            modelBuilder.Entity("MobixAPI.Models.AgentMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("AgentMessages");
                });

            modelBuilder.Entity("MobixAPI.Models.BenefitItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "🚚",
                            Order = 1,
                            Sub = "500₾-ზე მეტი შეკვეთისთვის",
                            Title = "უფასო მიწოდება"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "🔄",
                            Order = 2,
                            Sub = "უპრობლემოდ",
                            Title = "14 დღე დაბრუნება"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "🛡️",
                            Order = 3,
                            Sub = "24 თვე",
                            Title = "ოფიციალური გარანტია"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "💳",
                            Order = 4,
                            Sub = "12 თვეზე",
                            Title = "0% განვადება"
                        });
                });

            modelBuilder.Entity("MobixAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MobixAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "📱",
                            Name = "Smartphones",
                            NameGe = "სმარტფონები",
                            Slug = "smartphones"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "💻",
                            Name = "Laptops",
                            NameGe = "ლეპტოპები",
                            Slug = "laptops"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "📺",
                            Name = "TVs",
                            NameGe = "ტელევიზორები",
                            Slug = "tvs"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "📟",
                            Name = "Tablets",
                            NameGe = "ტაბლეტები",
                            Slug = "tablets"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "🎧",
                            Name = "Audio",
                            NameGe = "აუდიო",
                            Slug = "audio"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "📷",
                            Name = "Cameras",
                            NameGe = "კამერები",
                            Slug = "cameras"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "🎮",
                            Name = "Gaming",
                            NameGe = "გეიმინგი",
                            Slug = "gaming"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "🏠",
                            Name = "Smart Home",
                            NameGe = "სმარტ ჰომი",
                            Slug = "smart-home"
                        });
                });

            modelBuilder.Entity("MobixAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MobixAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MobixAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasInstallment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstallmentMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchAlias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(1180),
                            Description = "Apple iPhone 15 Pro Max 256GB Natural Titanium",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = true,
                            IsPublished = true,
                            Name = "iPhone 15 Pro Max 256GB",
                            OldPrice = 4299m,
                            Price = 3999m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 234,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 15,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(3946),
                            Description = "Samsung Galaxy S24 Ultra 512GB Titanium Black",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Samsung Galaxy S24 Ultra 512GB",
                            OldPrice = 3799m,
                            Price = 3499m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 189,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 20,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(3954),
                            Description = "Apple iPhone 15 128GB Blue",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "iPhone 15 128GB",
                            OldPrice = 2999m,
                            Price = 2799m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 312,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 30,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(3961),
                            Description = "Samsung Galaxy A55 5G 256GB Awesome Lilac",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Samsung Galaxy A55 5G",
                            OldPrice = 1399m,
                            Price = 1199m,
                            Rating = 4.5,
                            ReviewCount = 156,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 45,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Xiaomi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(3966),
                            Description = "Xiaomi 14 Pro 512GB Black",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Xiaomi 14 Pro 512GB",
                            OldPrice = 2699m,
                            Price = 2499m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 98,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 25,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Google",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(3989),
                            Description = "Google Pixel 8 Pro 256GB Obsidian",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Google Pixel 8 Pro 256GB",
                            OldPrice = 2499m,
                            Price = 2299m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 145,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 18,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Apple",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(3994),
                            Description = "Apple MacBook Pro 14-inch M3 Pro 18GB RAM 512GB SSD",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = true,
                            IsPublished = true,
                            Name = "MacBook Pro 14\" M3 Pro",
                            OldPrice = 6299m,
                            Price = 5999m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 178,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 12,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Dell",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(3999),
                            Description = "Dell XPS 15 OLED Intel Core i7 32GB 1TB",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Dell XPS 15 OLED",
                            OldPrice = 4999m,
                            Price = 4599m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 89,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 8,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "ASUS",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4004),
                            Description = "ASUS ROG Zephyrus G14 AMD Ryzen 9 16GB RTX 4060",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "ASUS ROG Zephyrus G14",
                            OldPrice = 3599m,
                            Price = 3299m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 134,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 10,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4008),
                            Description = "Lenovo ThinkPad X1 Carbon Gen 11 Intel i7 16GB 512GB",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Lenovo ThinkPad X1 Carbon",
                            OldPrice = 4199m,
                            Price = 3899m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 67,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 15,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Samsung",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4013),
                            Description = "Samsung 65 inch QLED 4K Smart TV Q80C 2023",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Samsung 65\" QLED 4K Q80C",
                            OldPrice = 3299m,
                            Price = 2899m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 89,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 7,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "LG",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4017),
                            Description = "LG 55 inch OLED 4K Smart TV C3 2023",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1571415060716-baff5b4bce74?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "LG OLED 55\" C3",
                            OldPrice = 3899m,
                            Price = 3499m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 112,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 5,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Sony",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4036),
                            Description = "Sony Bravia XR 65 inch OLED 4K Google TV",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Sony Bravia XR 65\" OLED",
                            OldPrice = 4799m,
                            Price = 4299m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 76,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 6,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Apple",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4041),
                            Description = "Apple iPad Pro 12.9-inch M2 256GB WiFi Space Gray",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "iPad Pro 12.9\" M2 256GB",
                            OldPrice = 3799m,
                            Price = 3499m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 201,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 20,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Samsung",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4045),
                            Description = "Samsung Galaxy Tab S9+ 12.4\" 256GB WiFi Beige",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Samsung Galaxy Tab S9+",
                            OldPrice = 2999m,
                            Price = 2699m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 134,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 14,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Apple",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4050),
                            Description = "Apple AirPods Pro 2nd Generation with MagSafe Case",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "AirPods Pro 2nd Gen",
                            OldPrice = 899m,
                            Price = 799m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 456,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 50,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Sony",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4055),
                            Description = "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Sony WH-1000XM5",
                            OldPrice = 1199m,
                            Price = 999m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 389,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 30,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "JBL",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4059),
                            Description = "JBL Charge 5 Portable Bluetooth Speaker Blue",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "JBL Charge 5",
                            OldPrice = 599m,
                            Price = 499m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 267,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 40,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Sony",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4064),
                            Description = "Sony PlayStation 5 Console with Ultra HD Blu-ray",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "PlayStation 5 Disc Edition",
                            OldPrice = 2399m,
                            Price = 2199m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 567,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 10,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Microsoft",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4081),
                            Description = "Microsoft Xbox Series X 1TB Console",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Xbox Series X 1TB",
                            OldPrice = 2199m,
                            Price = 1999m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 423,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 12,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Apple iPhone 14 Pro 256GB Deep Purple",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "iPhone 14 Pro 256GB",
                            OldPrice = 3299m,
                            Price = 2999m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 445,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 22,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4115),
                            Description = "Samsung Galaxy S23 FE 256GB Graphite",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Samsung Galaxy S23 FE 256GB",
                            OldPrice = 1699m,
                            Price = 1499m,
                            Rating = 4.5,
                            ReviewCount = 210,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 35,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Nothing",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4120),
                            Description = "Nothing Phone (2) 256GB White",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Nothing Phone (2) 256GB",
                            OldPrice = 1999m,
                            Price = 1799m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 134,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 18,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "OnePlus",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4125),
                            Description = "OnePlus 12 512GB Silky Black",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "OnePlus 12 512GB",
                            OldPrice = 2399m,
                            Price = 2199m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 167,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 20,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Xiaomi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4129),
                            Description = "Xiaomi Redmi Note 13 Pro 256GB Midnight Black",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Xiaomi Redmi Note 13 Pro 256GB",
                            OldPrice = 899m,
                            Price = 799m,
                            Rating = 4.4000000000000004,
                            ReviewCount = 523,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 60,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4134),
                            Description = "Samsung Galaxy Z Flip5 256GB Mint",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Samsung Galaxy Z Flip5 256GB",
                            OldPrice = 3199m,
                            Price = 2899m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 98,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 12,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Apple",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4139),
                            Description = "Apple MacBook Air 15-inch M2 8GB 256GB Midnight",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "MacBook Air 15\" M2 256GB",
                            OldPrice = 4299m,
                            Price = 3999m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 234,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 20,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "HP",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4157),
                            Description = "HP Spectre x360 14-inch Intel Core i7 16GB 512GB",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "HP Spectre x360 14\"",
                            OldPrice = 3799m,
                            Price = 3499m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 78,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 9,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Microsoft",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4162),
                            Description = "Microsoft Surface Laptop 5 13.5\" Intel i5 8GB",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Microsoft Surface Laptop 5",
                            OldPrice = 2999m,
                            Price = 2799m,
                            Rating = 4.5,
                            ReviewCount = 56,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 11,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Acer",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4166),
                            Description = "Acer Predator Helios 16 Intel i9 32GB RTX 4080",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Acer Predator Helios 16",
                            OldPrice = 5499m,
                            Price = 4999m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 89,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 6,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Samsung",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4171),
                            Description = "Samsung Galaxy Buds2 Pro Graphite ANC Wireless",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Samsung Galaxy Buds2 Pro",
                            OldPrice = 549m,
                            Price = 449m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 312,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 45,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Bose",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4176),
                            Description = "Bose QuietComfort 45 Wireless Noise Cancelling",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Bose QuietComfort 45",
                            OldPrice = 1099m,
                            Price = 899m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 289,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 25,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "JBL",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4181),
                            Description = "JBL Flip 6 Portable Waterproof Bluetooth Speaker",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "JBL Flip 6 Bluetooth Speaker",
                            OldPrice = 399m,
                            Price = 329m,
                            Rating = 4.5,
                            ReviewCount = 445,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 55,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Marshall",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4185),
                            Description = "Marshall Stanmore III Bluetooth Home Speaker Black",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Marshall Stanmore III Bluetooth",
                            OldPrice = 899m,
                            Price = 799m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 156,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 15,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Apple",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4203),
                            Description = "Apple iPad Air 5th Generation 64GB WiFi Blue",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "iPad Air 5th Gen 64GB",
                            OldPrice = 2499m,
                            Price = 2299m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 178,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 25,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Apple",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4208),
                            Description = "Apple iPad Mini 6th Generation 64GB WiFi Purple",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "iPad Mini 6th Gen 64GB",
                            OldPrice = 2099m,
                            Price = 1899m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 134,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 18,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Xiaomi",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4212),
                            Description = "Xiaomi Pad 6 Pro 12.4-inch 256GB WiFi Black",
                            HasInstallment = true,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Xiaomi Pad 6 Pro 256GB",
                            OldPrice = 1299m,
                            Price = 1099m,
                            Rating = 4.5,
                            ReviewCount = 89,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 22,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Samsung",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4217),
                            Description = "Samsung 55-inch Crystal UHD 4K Smart TV AU8000",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Samsung 55\" Crystal UHD 4K",
                            OldPrice = 1799m,
                            Price = 1499m,
                            Rating = 4.5,
                            ReviewCount = 234,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 12,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 39,
                            Brand = "LG",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4221),
                            Description = "LG 43-inch NanoCell 4K Smart TV NANO75 2023",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "LG 43\" NanoCell 4K",
                            OldPrice = 1199m,
                            Price = 999m,
                            Rating = 4.4000000000000004,
                            ReviewCount = 167,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 18,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Nintendo",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4226),
                            Description = "Nintendo Switch OLED Model White Joy-Con 64GB",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Nintendo Switch OLED",
                            OldPrice = 1699m,
                            Price = 1499m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 678,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 20,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Valve",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4231),
                            Description = "Valve Steam Deck 512GB OLED Limited Edition",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Steam Deck 512GB OLED",
                            OldPrice = 2399m,
                            Price = 2199m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 234,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 8,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Sony",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4248),
                            Description = "Sony DualSense Edge Wireless Controller for PS5",
                            HasInstallment = false,
                            ImageUrl = "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "DualSense Edge PS5 Controller",
                            OldPrice = 549m,
                            Price = 499m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 345,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 30,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Sony",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4253),
                            Description = "Sony Alpha A7 IV Full-Frame Mirrorless Camera Body",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Sony Alpha A7 IV",
                            OldPrice = 5999m,
                            Price = 5499m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 123,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 6,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Canon",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4258),
                            Description = "Canon EOS R6 Mark II Mirrorless Camera Body",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Canon EOS R6 Mark II",
                            OldPrice = 5299m,
                            Price = 4799m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 98,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 7,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 45,
                            Brand = "GoPro",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4262),
                            Description = "GoPro Hero 12 Black 5.3K Action Camera Waterproof",
                            HasInstallment = false,
                            ImageUrl = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "GoPro Hero 12 Black",
                            OldPrice = 999m,
                            Price = 899m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 567,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 35,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 46,
                            Brand = "DJI",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4267),
                            Description = "DJI Mini 4 Pro 4K HDR Drone with RC 2 Controller",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = true,
                            IsNew = true,
                            IsPublished = true,
                            Name = "DJI Mini 4 Pro Drone",
                            OldPrice = 2999m,
                            Price = 2799m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 189,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 10,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Apple",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4271),
                            Description = "Apple HomePod 2nd Generation Smart Speaker Midnight",
                            HasInstallment = false,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = false,
                            IsPublished = true,
                            Name = "Apple HomePod 2nd Gen",
                            OldPrice = 1099m,
                            Price = 999m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 234,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 20,
                            Variants = "[]"
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Xiaomi",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2026, 7, 1, 14, 5, 59, 445, DateTimeKind.Utc).AddTicks(4276),
                            Description = "Xiaomi Robot Vacuum X20 Pro 6000Pa Laser Navigation",
                            HasInstallment = true,
                            ImageUrl = "https://images.unsplash.com/photo-1589782182703-2aaa69037b5b?w=400",
                            Images = "[]",
                            InstallmentMonths = 12,
                            IsFeatured = false,
                            IsNew = true,
                            IsPublished = true,
                            Name = "Xiaomi Robot Vacuum X20 Pro",
                            OldPrice = 1499m,
                            Price = 1299m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 312,
                            SearchAlias = "",
                            Specs = "{}",
                            Stock = 15,
                            Variants = "[]"
                        });
                });

            modelBuilder.Entity("MobixAPI.Models.AgentMessage", b =>
                {
                    b.HasOne("MobixAPI.Models.AgentChat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("MobixAPI.Models.CartItem", b =>
                {
                    b.HasOne("MobixAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MobixAPI.Models.Category", b =>
                {
                    b.HasOne("MobixAPI.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MobixAPI.Models.OrderItem", b =>
                {
                    b.HasOne("MobixAPI.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobixAPI.Models.Product", b =>
                {
                    b.HasOne("MobixAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MobixAPI.Models.AgentChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MobixAPI.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("MobixAPI.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
